### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by keisukesueta** [keisukesueta/furima-37880#22]
# What
フリマアプリの挙動の確認
# Why
フリマアプリの挙動の確認のため

自身のフリマアプリのURL | https://furima-37880.herokuapp.com/
Basic認証のIDとパスワード |  ID 'admin' password '2222'
出品者用のメールアドレスとパスワード | 'keisuke@com'  's11111'
購入者用のメールアドレスとパスワード | 'keisuke2@com'　's11111'

挙動の確認お願いします。

**Comment by shodai-ito** [comment]
@keisukesueta さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
スポーツ・レジャーの後に不要な・が残っています。
<img width="400" alt="スクリーンショット 2022-05-20 14 35 42" src="https://user-images.githubusercontent.com/62537107/169459012-71eaf26e-af6d-4b88-9ceb-8ef757829776.png">

- [x] **配送料の負担は、「---、着払い(購入者負担)、送料込み(出品者負担)」の3項目が表示されること（--- は初期値として設定すること）**
「送料払い」と表示されておりますので、文言を見本と同様にしましょう。
<img width="374" alt="スクリーンショット 2022-05-20 14 36 57" src="https://user-images.githubusercontent.com/62537107/169459123-49449627-7a4a-4a22-90ad-f8d908f700fd.png">

- [x] **商品が出品されていない状態では、ダミーの商品情報が表示されること**
既に商品が出品されておりダミーが確認できなかった為、一度本番環境のデータベースをリセットいただいた上で、再度提出いただきたく存じます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by keisukesueta** [comment]
# What
フリマアプリの挙動の確認

# Why
フリマアプリの挙動の確認のため

自身のフリマアプリのURL | https://furima-37880.herokuapp.com/
Basic認証のIDとパスワード |  ID 'admin' password '2222'
出品者用のメールアドレスとパスワード | 'keisuke@com' 's11111'
購入者用のメールアドレスとパスワード | 'keisuke2@com'　's11111'

再度挙動の確認お願いします。

**Comment by yusuketono** [comment]
@keisukesueta さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/7105

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。

![lgtm_01](https://user-images.githubusercontent.com/51428519/169463780-8e1023ff-5cd3-485c-b0a5-28325ad7ea56.png)
